spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:ORCL
    username: GREENMRO
    password: GREENMRO
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
server:
  port: 9090
